config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#home"

  get 'user/login', :to => 'sessions#login'
  post 'user/login', :to=> 'sessions#verify_creds'
  get 'user/verify_otp', :to=> 'sessions#verify_otp'
  post 'user/verify_otp', :to=> 'sessions#verify_otp'
  delete 'user/logout', :to=> 'sessions#logout'

  get 'user/account_settings', :to => 'users#account_settings'
  get 'user/cart', :to => 'orders#cart'
  post 'user/new_address', :to=> 'users#new_address'
  post 'order/add_to_cart', :to => 'orders#add_to_cart'
  post 'order/remove_from_cart', :to=> 'orders#remove_from_cart'
  get 'order/checkout', :to=> 'orders#checkout'
  post 'order/order_confirmation', :to=> 'orders#submit_order'
  get 'order/icart', :to=> 'orders#icart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #Admin
  get 'qwe/admin', :to=> 'admin#admin_home'
  get 'qwe/admin/items_list', :to=> 'admin#items_list'
  post 'qwe/admin/new_item', :to=> 'admin#new_item'
  get 'qwe/admin/orders_list', :to => 'admin#orders_list'
end

app/views/admin/_admin_items_form.html.erb
<%= form_for(:new_item, :url=> qwe_admin_new_item_path, :remote => true) do |form| %>
  <% if item.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= pluralize(item.errors.count, "Error") %> :</h3>
      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Item Name" %>
    <br>
    <%= form.text_field :itm_name %>
  </div>
  <div class="field">
    <%= form.label :"Item Price" %>
    <br>
    <%= form.text_field :itm_price %>
  </div>
  <div class="field">
    <%= form.label :"Item Quantity" %>
    <br>
    <%= form.text_field :itm_qty %>
  </div>
  <div class="field">
    <%= form.label :"Item Guage Unit" %>
    <br>
    <%= form.text_field :itm_g_u %>
  </div>
  <div class="field">
    <%= form.label :"Item Inventory Quantity" %>
    <br>
    <%= form.text_field :itm_inv_qty %>
  </div>
  <div class="field">
    <%= form.label :"Item Catagory" %>
    <br>
    <%= form.select :itm_ctg, @item_categories%>
  </div>
  <div class="field">
    <%= form.label :"Item Wholesale Contact" %>
    <br>
    <%= form.text_field :itm_wslae_cntct %>
  </div>
  <div class="field">
    <%= form.label :"Item Image Upload" %>
    <br>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <div class="form-btn">
      <%= form.submit %>
    </div>
  </div>
<%end%>

app/views/admin/_admin_login.html.erb
<h1 style="margin-left: 40%; margin-top: 5%;">Log In</h1>
<div class="custom-form">
  <%= form_for(:session_data, :url => user_login_path) do |form| %>
    <% if @error %>
      <div class="alert alert-danger">
        <ul>
          <li>
            <%=@error%>
          </li>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :phone%>
      <br>
      <%= form.text_field :phone%>
    </div>
    <div class="field">
      <%= form.label :"Password" %>
      <br>
      <%= form.password_field :password %>
    </div>
    <%= form.hidden_field :admin_login, value: true%>
    <div class="actions">
      <div class="form-btn">
        <%= form.submit "Login"%>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/_admin_navbar.html.erb
<nav class="navbar admin-navbar-custom navbar-expand-md navbar-light">
  <%= link_to "Online Grocers", "/qwe/admin", :class=> "navbar-brand admin-custom-navbar-brand"%>
  <form class="form-inline admin-navbar-form">
    <%if is_admin_logged_in? %>
      <%= link_to "Items", "/qwe/admin/items_list", :method => "get", :class => "btn admin-navbar-btn" %>
      <%= link_to "Orders", "/qwe/admin/orders_list", :method => "get", :class => "btn admin-navbar-btn" %>
      <%= link_to "Log Out", user_logout_path(:admin_logout => true), :method => "delete", :class => "btn admin-navbar-btn" %>

    <%end%>
  </form>

</nav>

app/views/admin/admin_home.html.erb
<%if !is_admin_logged_in?%>
  <%=render "admin/admin_login"%>
<%end%>

app/views/admin/item_list.html.erb
<div class="admin_item_crud">
  <a href="javascript:void(0)" class="btn admin-btn" id="addItems">Add Item</a>
  <a href="javascript:void(0)" class="btn admin-btn" id="editItems">Edit Item</a>
</div>
<div id="newItem">
  <%= render 'admin/admin_items_form', :item => @new_item %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Item Name</th>
      <th scope="col">Item Price</th>
      <th scope="col">Item Quantity</th>
      <th scope="col">Item Guage Unit</th>
      <th scope="col">Item Inventory Quantity</th>
      <th scope="col">Catagory</th>
      <th scope="col">Item Image</th>
      <th scope="col">Wholesale Contact</th>
    </tr>
  </thead>
  <tbody>
    <%(0..@items.size-1).each do |i| %>
      <tr>
        <th scope="row"><%=i+1%></th>
        <td><%=@items[i][:itm_name] %></td>
        <td><%=@items[i][:itm_price]%></td>
        <td><%=@items[i][:itm_qty]%></td>
        <td><%=@items[i][:itm_g_u]%></td>
        <td><%=@items[i][:itm_inv_qty]%></td>
        <td><%=@items[i][:itm_ctg]%></td>
        <td><%= image_tag @items[i].image.url ,class: 'admin-list-image'%></td>
        <td><%=@items[i][:itm_wslae_cntct]%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<script>
  $('document').ready(function(){
    $('#newItem').hide();
    $('#addItems').click(function(){
      $('#newItem').toggle();
    })
  });
</script>

app/views/admin/items_list.html.erb
<div class="admin_item_crud">
  <a href="javascript:void(0)" class="btn admin-btn" id="addItems">Add Item</a>
  <a href="javascript:void(0)" class="btn admin-btn" id="editItems">Edit Item</a>
</div>
<div id="newItem">
  <%= render 'admin/admin_items_form', :item => @new_item %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Item Name</th>
      <th scope="col">Item Price</th>
      <th scope="col">Item Quantity</th>
      <th scope="col">Item Guage Unit</th>
      <th scope="col">Item Inventory Quantity</th>
      <th scope="col">Catagory</th>
      <th scope="col">Item Image</th>
      <th scope="col">Wholesale Contact</th>
    </tr>
  </thead>
  <tbody>
    <%(0..@items.size-1).each do |i| %>
      <tr>
        <th scope="row"><%=i+1%></th>
        <td><%=@items[i][:itm_name] %></td>
        <td><%=@items[i][:itm_price]%></td>
        <td><%=@items[i][:itm_qty]%></td>
        <td><%=@items[i][:itm_g_u]%></td>
        <td><%=@items[i][:itm_inv_qty]%></td>
        <td><%=@items[i][:itm_ctg]%></td>
        <td><%= image_tag @items[i].image.url ,class: 'admin-list-image'%></td>
        <td><%=@items[i][:itm_wslae_cntct]%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<script>
  $('document').ready(function(){
    $('#newItem').hide();
    $('#addItems').click(function(){
      $('#newItem').toggle();
    })
  });
</script>

app/views/admin/orders_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Order Id</th>
      <th scope="col">Buyer Id</th>
      <th scope="col">Buyer Name</th>
      <th scope="col">Order Status</th>
      <th scope="col">Items</th>
      <th scope="col">Delivery Address</th>
      <th scope="col">Razorpay Order Id</th>
    </tr>
  </thead>
  <tbody>
    <%(0..@orders.size-1).each do |i|%>
      <tr>
        <td><%=i+1%></td>
        <td><%=@orders[i][:order_id]%></td>
        <td></td>
        <td><%=@orders[i][:buyer_fname]%></td>
        <td><%=@orders[i][:order_status]%></td>
        <td>
          <%(@orders[i].cart.items.first(5)).each do |k,v|%>
            <%=k%>
            <br>
          <%end%>
        </td>
        <td><%=@orders[i][:dlvry_addr]%></td>
        <td><%=@orders[i][:rp_order_id]%></td>
      <tr>
    <%end%>
  </tbody>
</table>