config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#home"

  get 'user/login', :to => 'sessions#login'
  post 'user/login', :to=> 'sessions#verify_creds'
  get 'user/verify_otp', :to=> 'sessions#verify_otp'
  post 'user/verify_otp', :to=> 'sessions#verify_otp'
  delete 'user/logout', :to=> 'sessions#logout'

  get 'user/account_settings', :to => 'users#account_settings'
  get 'user/cart', :to => 'orders#cart'
  post 'user/new_address', :to=> 'users#new_address'
  post 'order/add_to_cart', :to => 'orders#add_to_cart'
  post 'order/remove_from_cart', :to=> 'orders#remove_from_cart'
  get 'order/checkout', :to=> 'orders#checkout'
  post 'order/order_confirmation', :to=> 'orders#submit_order'
  get 'order/icart', :to=> 'orders#icart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #Admin
  get 'qwe/admin', :to=> 'admin#admin_home'
  get 'qwe/admin/items_list', :to=> 'admin#items_list'
  post 'qwe/admin/new_item', :to=> 'admin#new_item'
  get 'qwe/admin/orders_list', :to => 'admin#orders_list'
end

app/views/users/account_settings/as_partials/_new_address.html.erb
<div id="newAddressForm">
  <div class="custom-form">
    <%= form_for(:new_address, :url=> user_new_address_path, html: { id: "newAddressForm1" }, :remote => true) do |form| %>
      <div class="alert alert-danger" id="errorBlock">
        <h3 id="errorBlock1"></h3>
        <ul id="errorBlock2">
        </ul>
      </div>

      <div class="field">
        <%= form.label :"Full Name" %>
        <br>
        <%= form.text_field :full_name %>
      </div>

      <div class="field">
        <%= form.label :"Street 1" %>
        <br>
        <%= form.text_field :street1 %>
      </div>

      <div class="field">
        <%= form.label :"Street 2" %>
        <br>
        <%= form.text_field :street2 %>
      </div>

      <div class="field">
        <%= form.label :"Area" %>
        <br>
        <%= form.text_field :area %>
      </div>

      <div class="field">
        <%= form.label :"District" %>
        <br>
        <%= form.text_field :district %>
      </div>


      <div class="field">
        <%= form.label :"State" %>
        <br>
        <%= form.text_field :state %>
      </div>

      <div class="field">
        <%= form.label :"Pin Code" %>
        <br>
        <%= form.text_field :pin %>
      </div>

      <div class="field">
        <%= form.label :"Contact Phone Number" %>
        <br>
        <%= form.text_field :contact_number %>
      </div>

      <div class="field">
        <%= form.label :"Landmark" %>
        <br>
        <%= form.text_field :landmark %>
      </div>

      <div class="actions" id="newAddressFormBtn">
          <%= form.submit "Submit", :class=>"btn new_address_btn " %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/account_settings/as_partials/_show_address.html.erb
<input type="button" id = "newAddress" value="New Address" class = "btn new_address_btn">
<div id="addressList">
  <table class="table table-striped">
    <tbody>
      <%@addresses.each do |address|%>
      <tr>
        <td>
          <%=address[:full_name]%><br>
          <%=address[:street1]%><br>
          <%=address[:area]%><br>
          <%=address[:district]%><br>
          <%=address[:pin]%><br>
          <%=address[:state]%><br>
          <%=address[:contact_number]%>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>