config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#home"

  get 'user/login', :to => 'sessions#login'
  post 'user/login', :to=> 'sessions#verify_creds'
  get 'user/verify_otp', :to=> 'sessions#verify_otp'
  post 'user/verify_otp', :to=> 'sessions#verify_otp'
  delete 'user/logout', :to=> 'sessions#logout'

  get 'user/account_settings', :to => 'users#account_settings'
  get 'user/cart', :to => 'orders#cart'
  post 'user/new_address', :to=> 'users#new_address'
  post 'order/add_to_cart', :to => 'orders#add_to_cart'
  post 'order/remove_from_cart', :to=> 'orders#remove_from_cart'
  get 'order/checkout', :to=> 'orders#checkout'
  post 'order/order_confirmation', :to=> 'orders#submit_order'
  get 'order/icart', :to=> 'orders#icart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #Admin
  get 'qwe/admin', :to=> 'admin#admin_home'
  get 'qwe/admin/items_list', :to=> 'admin#items_list'
  post 'qwe/admin/new_item', :to=> 'admin#new_item'
  get 'qwe/admin/orders_list', :to => 'admin#orders_list'
end

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-custom navbar-expand-md navbar-light">
  <%= link_to "Online Grocers", root_path, :class=> "navbar-brand"%>
  <button id="navburger" class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navbarMenu" class="collapse navbar-collapse">
    <form class="form-inline">
      <input class="navbar-search" type="search" placeholder="Search" aria-label="Search">
      <button class="btn" type="submit">Search</button>
      <% if logged_in? %>
        <%= link_to "Account Settings", user_account_settings_path, :method => "get", :class => "btn" %>
        <%= link_to "Log Out", user_logout_path(:admin_logout => is_admin_logged_in?), :method => "delete", :class => "btn" %>
      <% else %>
        <%= link_to "Log In", user_login_path, :method => "get", :class => "btn"%>
        <%= link_to "Sign Up", new_user_path, :method => "get", :class => "btn" %>
      <% end %>
      <a href="/user/cart"><%= image_tag 'shopping_cart.png', class: 'shopping-cart'%></a>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Grocer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%if controller.class.name.split("::").first=="AdminController"%>
      <%= render "admin/admin_navbar"%>
    <%else%>
      <%= render "layouts/user_navbar"%>
    <%end%>

  </head>

  <body style="background-color: #FEF9E7;">
    <%= yield %>
  </body>

  <script>
    $(document).ready(function () {
      var isNavCollapsed = true;
      $('#navburger').click(function(){

      });
    });
  </script>
</html>